### PR TITLE
Add TeaVM client

### PR DESCRIPTION
**Pull request by konsoletyper**
Add TeaVM client that builds with TeaVM 0.3.0. However, there is [bug](https://github.com/konsoletyper/teavm/issues/132) in `java.util.Logger` implementation, so I had to include little hack that removes all calls to `java.util.Logger` methods. I'll fix it in the next minor release in few days, so no hacks will be necessary with 0.3.1

Sadly, I could not run current bck2brwsr implementation. Additionally, I had to change game logic, since the current logic causes `Hooray` message to appear immediately. Also I slightly altered boot code in `index.html`

### CODE REVIEW

**Comment by jtulach** [comment]
Why there are dependencies on bck2brwsr?

ko-bck2brwsr is just an empty wrapper around ko4j.

Do you read classes from the emul JAR?

**Comment by konsoletyper** [comment]
You are right. I just copy-pasted dependencies from `client-web`. I removed these dependencies and everyting works fine. Also, I set the `provided` scope for remaining dependencies, since there's no need in copying jar files to `WEB-INF/lib`.

**Comment by dukescript** [comment]
Thanks for the pull request. I've tried the demo and it works fine. So I'm merging this now. For further integration (adding TeaVM by default to the archetypes) we should probably browse this locally from the target dir instead of packaging and launching a war.

**Comment by konsoletyper** [comment]
> we should probably browse this locally from the target dir instead of packaging and launching a war.

I disagree. WAR file is standard way of deploying web apps, with all of its pros and cons. First, I work in Eclipse, and there is WTP, which automatically redeploys static resource on every change. Combined with Eclipse's incremental builder and TeaVM's plugin for Eclipse, it is possible to avoid manual work to redeploy. I just change my classes, save them in the editor and press `refresh` in the browser. With assemblies, I have to rerun the entire maven build and wait for several seconds.

I guess we should wait until I release TeaVM 0.3.1 in few days, since 0.3.0 has critical issue in `Logger` implementation.

What about inability to run bck2brwsr version? And what about the following code:

``` java
   return new Game(0, 0, true, tiles.toArray(new Tile[16]));
```

I changed `true` to `false` here, since `true` caused "Hooray" message to appear immediately.

**Comment by dukescript** [comment]
> I guess we should wait until I release TeaVM 0.3.1 in few days, since 0.3.0 has critical issue in Logger implementation.

OK, let me know when it is available.

> What about inability to run bck2brwsr version?

Seems to have been caused by refactoring. bck2brwsr is looking for fifteen.js, the name of the file is fifteenpuzzle.js. I’ll fix that.

> And what about the following code:
> 
>    return new Game(0, 0, true, tiles.toArray(new Tile[16]));
> I changed true to false here, since true caused "Hooray" message to appear immediately.
> 
> A bug, it probably never happened to me because of local storage, which should give you persisted state from last game and overrides what is done in initGame. thanks for spotting it.

Am 30.06.2015 um 13:40 schrieb Alexey Andreev notifications@github.com:

**Comment by dukescript** [comment]
should be fixed now.

Am 30.06.2015 um 14:04 schrieb Anton Epple toni.epple@eppleton.de:

> > What about inability to run bck2brwsr version?
> 
> Seems to have been caused by refactoring. bck2brwsr is looking for fifteen.js, the name of the file is fifteenpuzzle.js. I’ll fix that.

**Pull request merged**
